config/routes.rb
Rails.application.routes.draw do
  #Root
  root('static#welcome')

  #Signup
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  #App Log-in & Log-out
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: "sessions#logout"

  #Spotifiy Callback
  get '/auth/spotify/callback', to: 'sessions#omniauth'
  get '/search', to: 'playlists#search', as: 'search'

  #Like and Dislike a Playlist WIP
  post '/playlists/:id/dislike', to: 'playlist#dislike', as: 'dislike_playlist'
  post '/playlists/:id/like', to: 'playlist#like', as: 'like_playlist'
  get '/playlists/:id/player', to: 'playlists#player', as: 'player_playlist'
  #renders a player pages for a given playlist

  resources :tracks
  resources :playlists, only: [:new, :create, :destroy]
  #CUSTOM ROUTES to handle direct spotify import cludge
  get '/playlists/import', to: 'playlists#import', as: 'import_playlist'
  post '/playlists/import', to: 'playlists#spotify_create', as: 'spotify_import'

  resources :playlists do
    resources :comments, only: [:new, :create, :destroy]
    #New is just a placeholder form for handling serialzed Playlist objects when a spotify user signs in. 
    #Import is a custom route that will import a playlist and it's tracks from a public spotify ID key
    resources :tracks, only: [:index]
  end

  resources :users do
    resources :comments, only: [:index, :destroy]
    #just index and deletion for now, editing will probably be better handled with JS framework
    resources :playlists, only: [:index, :show, :destroy]
    #show all user_playlists, show an individual one, and delete existing lists they own
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/track.rb
class Track < ApplicationRecord
    # Associations
    # A track may belong to many playlists
    belongs_to :playlist

    # Validations
    validates :name, presence: true
        #Prevents blank playlist names
    validates :spotify_id, presence: true
        #must have a spotify ID, which WIP can be used to pull additional information from RSpotify later if needed.

    # Scopes
    scope :search, -> (query) { self.where("name LIKE ?", "%#{query}%") }

    def self.new_from_spotify(spotify_track, passedplaylist_id = nil)
        #pass in a RSpotify track object to instance this class
        #byebug
        Track.new(
            name: spotify_track.name,
            spotify_id: spotify_track.id,
            artists: spotify_track.artists[0].name,
            #img: spotify_track.albums[0].images[0]["url"],
            url: spotify_track.external_urls,
            preview: spotify_track.preview_url,
            playlist_id: passedplaylist_id)  
    end

    def self.create_from_spotify(spotify_track, playlist_id = nil)
        track = self.new_from_spotify(spotify_track, playlist_id)
        track.save
        
    end

    def self.newTracks_from_playlist(spotify_playlist, passed_playlist_id)
        #Take passed playlist hash create local track objects
        spotify_playlist.tracks.each do |track|
            #byebug
            Track.create_from_spotify(track, passed_playlist_id)
        end
    end

    def self.createTracks_from_playlist(playlist)
        self.newTracks_from_playlist(playlist)
    end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    def index
        if params[:playlist_id] 
            @tracks = Playlist.find(params[:playlist_id]).tracks
        else
            @tracks = Track.all
        end
        #byebug
        #render json: @tracks 
    end

    def show
        @track = Track.find(params[:id])
    end

    def new
        @track = Track.new
    end

    private
    def get_track
        @track = Track.find_by(id: params[:id])
    end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_track.html.erb
<%# This partial is for keeping Track object views DRY%>
<%# 
create_table "tracks", force: :cascade do |t|
    t.string "name"
    t.string "spotify_id"
    t.string "artists"
    t.string "img"
    t.string "url"
    t.string "preview"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
 %>
<div class="card">
    <strong class="card-text"><%= track.name %></strong>
    <a href="<%= track_path(track) %>"><a>

</div>

app/views/tracks/index.html.erb
<h1>The Track-Dex</h1>
<table>
    <% @tracks.each do |track|%>
        <tr>
            <td><%=track.name %></td>
            <td><%=track.artists %></td>
            <td><%=track.name %></td>
        </tr>
    <% end %>
</table>
  

app/views/tracks/new.html.erb
<%# Temporary Page: Ideally will be replaced with better Spotify interfacing%>
<h1>New Track Placeholder Page </h1>

app/views/tracks/show.html.erb
<%= render partial: 'errors/errors', locals: {model: @track} %>

<%= render partials: 'tracks/track', locals: {track: @track} %>