config/routes.rb
Rails.application.routes.draw do
  #Root
  root('static#welcome')

  #Signup
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  #App Log-in & Log-out
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: "sessions#logout"

  #Spotifiy Callback
  get '/auth/spotify/callback', to: 'sessions#omniauth'
  get '/search', to: 'playlists#search', as: 'search'

  #Like and Dislike a Playlist WIP
  post '/playlists/:id/dislike', to: 'playlist#dislike', as: 'dislike_playlist'
  post '/playlists/:id/like', to: 'playlist#like', as: 'like_playlist'
  get '/playlists/:id/player', to: 'playlists#player', as: 'player_playlist'
  #renders a player pages for a given playlist

  resources :tracks
  resources :playlists, only: [:new, :create, :destroy]
  #CUSTOM ROUTES to handle direct spotify import cludge
  get '/playlists/import', to: 'playlists#import', as: 'import_playlist'
  post '/playlists/import', to: 'playlists#spotify_create', as: 'spotify_import'

  resources :playlists do
    resources :comments, only: [:new, :create, :destroy]
    #New is just a placeholder form for handling serialzed Playlist objects when a spotify user signs in. 
    #Import is a custom route that will import a playlist and it's tracks from a public spotify ID key
    resources :tracks, only: [:index]
  end

  resources :users do
    resources :comments, only: [:index, :destroy]
    #just index and deletion for now, editing will probably be better handled with JS framework
    resources :playlists, only: [:index, :show, :destroy]
    #show all user_playlists, show an individual one, and delete existing lists they own
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/playlist.rb
class Playlist < ApplicationRecord
    belongs_to  :user
    has_many :tracks, dependent: :destroy

    has_many :comments, dependent: :destroy
    # `depedent: :destroy` will nuke comment children upon deletion of the parent playlist
    has_many :users, through: :comments
    
    validates :name, presence: true
    validates :spotifyPlaylistID, presence: true
    # RSpotify::Playlist.find_by_id('id', market: nil) -> Playlist
    # Today's Top 100
    # https://open.spotify.com/playlist/37i9dQZF1DXcBWIGoYBM5M

    scope :search, -> (query) { self.where("name LIKE ?", "%#{query}%") }
#
    def self.new_from_spotify(spotify_playlist, user_id = 2)
        #pass in an RSpotify playlist object
        #During seeding we assume Professor Reed is the User.all[1], but their Id is 2
        Playlist.new(
            name: spotify_playlist.name,
            user_id: user_id,
            description: spotify_playlist.description,
            spotifyPlaylistID: spotify_playlist.id,
            spotifyUserID: spotify_playlist.owner.id,
            followers: spotify_playlist.followers.count)
            
            #WIP, need to iterate though each track object, may need to pass additional arguments for proper ownership
            # spotify_playlist.tracks.each do |track|
            #    Track.create_from_spotify(track)
            # end        
            
    end

    def self.create_from_spotify(spotify_playlist, user_id = 2)
        #Need to add a user_id to this method params
        playlist = self.new_from_spotify(spotify_playlist, user_id)
        playlist.save
        Track.newTracks_from_playlist(spotify_playlist, playlist.id)
        return playlist
    end

# Spotify ID based Methods

    def self.find_from_spotify_id(spotify_id)
        # created to dry up seeding, and assist in building more complex methods
        return RSpotify::Playlist.find_by_id(spotify_id)

    end

    def self.create_from_spotify_id(spotify_id, user_id)
        self.create_from_spotify(
            self.find_from_spotify_id(spotify_id), 
            user_id)
            
    #need a method that uses the RSpotify playlist.tracks array to instance new local track objects 
    end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
    #Check if a user is logged in, then allow only #new, #create, & #update actions
    before_action :redirect_if_not_logged_in, only: [:new, :create, :update]

    def index
        @playlists = Playlist.all 
    end
    
    def show
        @playlist = Playlist.find(params[:id])
        #provides the set of comments to render
        @comments = @playlist.comments
        #preps for a new comment
        @comment = @playlist.comments.build(user_id: current_user.id)
        #sets the tracks to render
        @tracks = @playlist.tracks
        # WIP 
        #@playlist.update(views: @playlist.views+1)
    end
    def player
        @playlist = Playlist.find(params[:id])
    end

    def new
        #Provides a manual form for now till slightly less jank import action works
        @playlist = Playlist.new
        #This is an empty container, that is not yet saved to the DB
    end
    def import
        #creates an empty container 
        #TODO: send a form to input a spotify ID
        #use Playlist#create_from_spotify to pull all the data from a new playlist from spotify into the new container, and save it to the DB
        # Console example: test = Playlist.new_from_spotify(Playlist.find_from_spotify_id('1fAyMF8A9yuQmSTX3YjVOK'), user_id = 3)
        @playlist = Playlist.new(params[:spotify_id])
    end

    def spotify_create
        
        @playlist = Playlist.create_from_spotify_id(params[:spotify_id], current_user.id)
        redirect_to playlist_path(@playlist)
    end

    def create
        #WIP, should 
        byebug
        @playlist = Playlist.new(playlist_params)
        if @playlist.save
            redirect_to playlist_path(@playlist)
        else
            render :new
        end
    end

    def like
        #WIP
    end

    def search
        @playlists = Playlist.search(params[:name])
        render :index
    end

    def destroy
        @playlist = Playlist.find(params[:id])
        @playlist.destroy
        flash[:message] = "Playlist Deleted"
        redirect_to User.find(params[:user_id])
    end

    #-----Helpers & Private Methods------
    private
    def playlist_params
        params.require(:playlist).permit(:name, :user_id, :description, :spotifyPlaylistID, :spotifyUserID)
    end

    def import_params
        params.require(:playlist).permit(:spotify_id, :user_id)
    end
    def find_playlist
        @playlist = Playlist.find_by_id(params[:playlist_id])
    end
    
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_card.html.erb
<div class="card">
    <strong class="card-text"><%= playlist.name %></strong>
    <a href="<%= playlist_path(playlist) %>"><a>
    <p class="card-text"><%= playlist.views %></p>
    <p class="card-text"><%= playlist.likes %></p>
</div>

app/views/playlists/import.html.erb
<%#A form to import a specific Spotify Playlist by ID, using current user ID%>
<%# Refactor this later for better user experience%>

<%# test = Playlist.new_from_spotify(Playlist.find_from_spotify_id('1fAyMF8A9yuQmSTX3YjVOK'), user_id = 3)%>
<%# Playlist.create_from_spotify(params%>
<%#= render partial: 'errors/errors', locals: {model: @playlist} %>

<h3> Import a new Playlist from Spotify </h3>
<%= form_with(url: import_playlist_path, method: 'post') do |f|%>
    <%= f.text_field :spotify_id, class: "form-control me-2", placeholder: "Put Spotify Playlist ID Key here" %>
    <%= f.submit :new, class: 'btn btn-outline-success' %>
<% end %>

app/views/playlists/index.html.erb
<%# <%= index_header %> 
<h1>The Playlists</h1>
<%# Search Bar%>
<%= form_with(url: search_path, method: 'get', class: 'd-flex') do |f|%>
   <%= f.text_field :name, class: "form-control me-2", placeholder: "Search for Playlists" %>
   <%= f.submit :search, class: "btn btn-outline-success" %>
<% end %>

<%# List of all Playlists%>
<div class="album text-muted">
   <div class="container">
      <div class="row">
         <% @playlists.each do |p| %>
            <%#= Replace this with render partial: 'card', :playlist => p %>
            <a href="/playlists/<%= p.id %>" class="card" style="width: 15rm; display: inline-block">
               <div class="card-body">
                  <strong class="card-text"><%= p.name %></strong>
                  <p class="card-text">Views:<%= p.views %></p>
                  <p class="card-text">Score:<%= p.likes %></p>
                  
            </a>
         <% end %>
      </div>
    </div>
</div>

app/views/playlists/new.html.erb
<%#A form to import a specific Spotify Playlist by ID, using current user ID%>
<%# Ideally we will NEVER use this page%>

<%# test = Playlist.new_from_spotify(Playlist.find_from_spotify_id('1fAyMF8A9yuQmSTX3YjVOK'), user_id = 3)%>
<%# Playlist.create_from_spotify(params%>
<%= render partial: 'errors/errors', locals: {model: @playlist} %>

<h3> Import a new Playlist from Spotify Manually </h3>
<%= form_with(model: @playlist) do |f|%>
<ul>
    <div><%= f.label         :name %></div>
    <div><%= f.text_field    :name, placeholder: "Playlist Name "%></div>
    <div><%= f.label         :description %></div>
    <div><%= f.text_field    :description, placeholder: "Description"%></div>
    <div><%= f.label         :spotifyPlaylistID  %></div>
    <div><%= f.text_field    :spotifyPlaylistID, placeholder: "Spotify Playlist ID "%></div>
    <div><%= f.label         :spotifyUserID  %></div>
    <div><%= f.text_field    :spotifyUserID, placeholder: "Spotify User Name"%></div>
    <div><%= f.submit :new, class: 'btn btn-outline-success' %></div>
<% end %>

app/views/playlists/player.html.erb
<h1>Player for: <%=@playlist.name%> </h1>
<iframe src="https://open.spotify.com/embed/playlist/<%=@playlist.spotifyPlaylistID%>" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>

app/views/playlists/show.html.erb
<%= render partial: 'errors/errors', locals: {model: @playlist} %>

<h1><%= @playlist.name %></h1>
<div>
    <p> <%= @playlist.description %></p>
    <p> Created by:<%=if @playlist.spotifyUserID? 
        @playlist.spotifyUserID 
        else 
        User.find_by_id(@playlist.user_id).username 
        end %> </p>
    <p> Views: <%= @playlist.views %></p>
    <p> Likes: <%= @playlist.likes %></p>
    <p> Dislikes: <%= @playlist.dislikes %></p>
    <p> <%= link_to "Player", player_playlist_path(@playlist), method: 'get' %> </p>
</div>
<%# Like/Dislike buttons Here%>
<%#= button_to "Like", like_playlist(@playlist), class: 'button' %>
<%# Litterally Rails: button helper, it's lable, the url with (param), object class%>
<%#= button_to "Dislike", dislike_playlist(@playlist), class:'button'%>
<%# Render all the tracks in this playlist below, ideally with a common card partial %>

    <table>
        <% @playlist.tracks.each do |track|%>
            <tr>
                <td><%=track.name %></td>
                <td><%=track.artists %></td>
                <td><%=track.name %></td>
            </tr>
        <%end%>
    </table>


<h3>Drop some feedback on this banger of a playlist</h3>

<%= form_with(model: [@playlist, @comment]) do |f|%>
    <%= f.text_area     :body                                   %>
    <%= f.submit        :comment                                %>
<% end %>

<%# List comments below, sure why not use cards again? Ideally refactor this to use a common partial %>
<h3>Comments:</h3>
<% @comments.each do |comment|%>
    <%if comment.id?%>
        <div class="card">
            <strong><%=  comment.user.username %> Said:</strong> 
            <p><%= comment.body %></p>
            <p><small><%= comment.updated_at%></small></p>
        <div>
    <%end%>
<% end %>