config/routes.rb
Rails.application.routes.draw do
  #Root
  root('static#welcome')

  #Signup
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  #App Log-in & Log-out
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: "sessions#logout"

  #Spotifiy Callback
  get '/auth/spotify/callback', to: 'sessions#omniauth'
  get '/search', to: 'playlists#search', as: 'search'

  #Like and Dislike a Playlist WIP
  post '/playlists/:id/dislike', to: 'playlist#dislike', as: 'dislike_playlist'
  post '/playlists/:id/like', to: 'playlist#like', as: 'like_playlist'
  get '/playlists/:id/player', to: 'playlists#player', as: 'player_playlist'
  #renders a player pages for a given playlist

  resources :tracks
  resources :playlists, only: [:new, :create, :destroy]
  #CUSTOM ROUTES to handle direct spotify import cludge
  get '/playlists/import', to: 'playlists#import', as: 'import_playlist'
  post '/playlists/import', to: 'playlists#spotify_create', as: 'spotify_import'

  resources :playlists do
    resources :comments, only: [:new, :create, :destroy]
    #New is just a placeholder form for handling serialzed Playlist objects when a spotify user signs in. 
    #Import is a custom route that will import a playlist and it's tracks from a public spotify ID key
    resources :tracks, only: [:index]
  end

  resources :users do
    resources :comments, only: [:index, :destroy]
    #just index and deletion for now, editing will probably be better handled with JS framework
    resources :playlists, only: [:index, :show, :destroy]
    #show all user_playlists, show an individual one, and delete existing lists they own
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <%# Hell yeah lets get that vaporwave aesthetic in here %>
    <div id="BC-BGM-Player" data-turbolinks-permanent>
        <iframe style="border: 0; width: 100%; height: 42px;" src="https://bandcamp.com/EmbeddedPlayer/album=1412946879/size=small/bgcol=333333/linkcol=e32c14/transparent=true/" seamless><a href="https://luxuryelite.bandcamp.com/album/prism">prism by luxury elite</a></iframe>
        <hr class="solid">
    </div>
    <small>
        <a href="https://github.com/baldo-vela/greatest-hits">Greatest Hits </a> by Baldomero Vela 
    </small>
</footer>

app/views/layouts/_nav.html.erb
<%# Icon, probably need to set size with %'s, links to home page %>
<%# User Profile %>
<%# Search for playlists bar %>
<%# Search Bar %>
<nav class ="navbar">
        <ul class="navbar-nav">
          <li class="logo">
            <a href="/" class="nav-link">
              <%= image_tag('gh_logo.png', width: '40rem', height: '40rem') %>
              <span class="link-text logo-text">Greatest Hits </span>
            </a>
          </li>
        <% if logged_in? %> 
          <li class="nav-item">
            <a href="/users/<%= current_user.id %>" class="nav-link">
              <span class="link-text logo-text">User Profile </span>
            </a>
          </li>
           <li class="nav-item">
            <%=button_to 'Logout', logout_path, class: 'nav-link active', method: 'delete'%>
          </li>
        <% else %>
          <li>
            <%= button_to 'Login', login_path, class: 'nav-link active' %>
          </li>
          <li>
            <%= button_to 'Login with Spotify', '/auth/spotify', class: 'nav-link active', method: "post" %>
          </li>
          
          
        <% end %>
          <li class="nav-item">
            <a href="/playlists" class="nav-link">
              <span class="link-text logo-text">Playlists </span>
            </a>
          </li>
          <li>
            <%= form_with(url: search_path, method: 'get', class: 'd-flex') do |f|%>
              <%= f.text_field :name, class: "form-control me-2", placeholder: "Search for Playlist" %>
              <%= f.submit :Search, class: "btn btn-outline-success" %>
            <% end %>
          </li>
        </ul>
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Greatest-Hits</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('gh_favicon.ico') %>
    <meta name="turbolinks-root" content="/app">
    <%# Renders the nav bar%>
    <%= render(partial: "layouts/nav") %>
  </head>

  <body>
    
    <%# displays any flash messages%> 
    <%= flash[:message] %>
    <%# compelted view gets rendered here %> 
    <%= yield %>
  </body>
 <footer class="footer" data-turbolinks-permanent>
    <%# Hell yeah lets get that vaporwave aesthetic in here %>
    <div id="BC-BGM-Player" >
        <iframe style="border: 0; width: 100%; height: 42px;" src="https://bandcamp.com/EmbeddedPlayer/album=1412946879/size=small/bgcol=333333/linkcol=e32c14/transparent=true/" seamless><a href="https://luxuryelite.bandcamp.com/album/prism">prism by luxury elite</a></iframe>
        <hr class="solid">
    </div>
    <small>
        <a href="https://github.com/baldo-vela/greatest-hits">Greatest Hits </a> by Baldomero Vela 
    </small>
</footer>
</html>